config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    authenticate :user do
      get 'users/profile/edit', to: 'users/registrations#profile_edit', as: 'user_profile_edit'
      get 'users/profile', to: 'users/registrations#profile', as: 'user_profile'
      get 'users/account', to: 'users/registrations#account', as: 'user_account'
    end
  end

  resources :rooms do
    resources :reservations do
      post 'confirm', on: :collection
    end
  end

  resources :reservations
  get "myreservation", to: "reservations#myreservation", as: 'myreservation'
  get 'myrooms',to:'rooms#myrooms'
  get 'search',to:'rooms#search'
  get '/',to:'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validate :true_date
  validates_presence_of :check_in, :check_out, :headcount
  validates :headcount, presence: true, numericality: { greater_than_or_equal_to: 1 }


  def true_date
    if check_in.present? && check_out.present? && check_in >= check_out
      errors.add(:check_out, "チェックアウト日はチェックイン日より後にしてください")
    end
  end

  def calculate_total_price
    (self.room.price * self.headcount * (self.check_out - self.check_in).to_i).to_i
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
    @reservation = Reservation.new
  end

  def confirm
    @room = Room.find(params[:room_id])
    @reservation = @room.reservations.build(reservation_params)
    @reservation.user_id = current_user.id
    if @reservation.valid?
      flash.clear
      @reservation.price = @reservation.calculate_total_price
      session[:reservation_data] = reservation_params
      render :confirm
    else
      flash[:notice] = "入力エラーがあります"
      render "rooms/show"
    end
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      session.delete(:reservation_data)
      redirect_to myreservation_path
      flash[:notice] = "作成しました"
    else
      render "rooms/show"
    end
  end

  def destroy
    reservation = Reservation.find(params[:id])
    if reservation.destroy
      redirect_to myreservation_path
      flash[:notice] = "削除しました"
    end
  end

  def myreservation
    @reservations = current_user.reservations
  end

  private

  def reservation_params
    params.require(:reservation).permit(:check_in, :check_out, :headcount, :user_id, :room_id, :price)
  end
end

app/views/reservations/confirm.html.erb
<div class="confirm-contents">
  <div class="room-contents">
    <div class="room-image">
    <%= image_tag @reservation.room.image_name.url , size: "400x300" %>
    </div>
    <div class="room-text"">
      <h1><%= @reservation.room.name %></h1><br>
      <p><%= (@reservation.check_out - @reservation.check_in).to_i %>日</p>
      <p><%= @reservation.headcount %>人</p>
      <p><%= @reservation.price %>円</p><br>
      <%= @reservation.check_in %>〜
      <%= @reservation.check_out %>

      <%= form_with(url: reservations_path, method: :post, local: true) do |f| %>
       <%= hidden_field_tag 'reservation[check_in]', @reservation.check_in %>
       <%= hidden_field_tag 'reservation[check_out]', @reservation.check_out %>
       <%= hidden_field_tag 'reservation[headcount]', @reservation.headcount %>
       <%= hidden_field_tag 'reservation[user_id]', @reservation.user_id %>
       <%= hidden_field_tag 'reservation[room_id]', @reservation.room_id %>
       <%= hidden_field_tag 'reservation[price]', @reservation.price %>
       <%= f.submit "予約",class: "confirm-submit" %>
      <% end %>
    </div>
  </div>
</div>

app/views/reservations/myreservation.html.erb
<div class="my-reservation">
  <table>
    <tr>
      <th>画像</th>
      <th>名前</th>
      <th>住所</th>
      <th class="reservation-details">詳細</th>
      <th>料金</th>
      <th>人数</th>
      <th>日数</th>
      <th>チェックイン</th>
      <th>チェックアウト</th>
      <th>確定日時</th>
    </tr>
    <% @reservations.each do | r | %>
      <tr>
        <td><%= image_tag r.room.image_name.url, size: "130x80" %></td>
        <td><%= link_to r.room.name, room_path(r.room) %></td>
        <td><%= r.room.address %></td>
        <td class="reservation-details"><%= r.room.details %></td>
        <td><%= r.price %>円</td>
        <td><%= r.headcount %>人</td>
        <td><%= (r.check_out - r.check_in).to_i %>日</td>
        <td><%= r.check_in.in_time_zone('Tokyo').strftime('%Y/%m/%d') %></td>
        <td><%= r.check_out.in_time_zone('Tokyo').strftime('%Y/%m/%d') %></td>
        <td><%= r.created_at.in_time_zone('Tokyo').strftime('%Y/%m/%d %H:%M') %></td>
        <td><%= link_to "削除", r, method: :delete, data: { confirm: "本当に削除しますか?" }, class: "myreservation-d"%></td>
      </tr>
    <% end %>
  </table>
</div>