config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    authenticate :user do
      get 'users/profile/edit', to: 'users/registrations#profile_edit', as: 'user_profile_edit'
      get 'users/profile', to: 'users/registrations#profile', as: 'user_profile'
      get 'users/account', to: 'users/registrations#account', as: 'user_account'
    end
  end

  resources :rooms do
    resources :reservations do
      post 'confirm', on: :collection
    end
  end

  resources :reservations
  get "myreservation", to: "reservations#myreservation", as: 'myreservation'
  get 'myrooms',to:'rooms#myrooms'
  get 'search',to:'rooms#search'
  get '/',to:'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations

  validates :name, presence: true
  validates :details, presence: true
  validates :price, presence: true
  validates :address, presence: true

  validates :price, numericality: { greater_than_or_equal_to: 1 }


  mount_uploader :image_name, RoomImageUploader

  def self.search(address_keyword, details_keyword)
    where(["address like?", "%#{address_keyword}%"]).where(["name like? OR details like?", "%#{details_keyword}%", "%#{details_keyword}%"])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:edit, :update, :destroy,]
  before_action :authorize_user, only: [:edit, :update, :destroy, ]
  before_action :authenticate_user!, only: [:myrooms, :new]



  def myrooms
    if current_user
      @rooms = current_user.rooms
    else
      flash[:notice] = "権限がありません"
      redirect_to "/"
    end
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.user = current_user
    if @room.save
      if @room.image_name.present?
        @room.image_name = "#{@room.id}.jpg"
        @room.save
      end
      flash[:notice] = "作成しました"
      redirect_to "/"
    else
      flash[:notice] = "入力エラーがあります"
      render "new"
    end
  end

  def show
    @room = Room.find(params[:id])
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:notice] = "編集しました"
      redirect_to room_path(@room)
    else
      flash[:notice] = "入力エラーがあります"
      render "edit"
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    flash[:notice] = "削除しました"
    redirect_to myrooms_path
  end

  def search
    @rooms = Room.search(params[:address_keyword], params[:details_keyword])
    @address_keyword = params[:address_keyword]
    @details_keyword = params[:details_keyword]
    render "index"
  end

  def set_room
    @room = Room.find(params[:id])
  end

  def authorize_user
    unless current_user == @room.user
      flash[:notice] = "権限がありません"
      redirect_to "/"
    end
  end

  private

  def room_params
    params.require(:room).permit(:name, :address, :price, :details, :image_name, :user_id)
  end
end

app/views/rooms/edit.html.erb
<div class="room-form">
  <%= form_with model:@room do |f| %>
    <%= f.text_field :name, placeholder: "名前" %><br>
    <%= f.text_area :details, placeholder: "詳細" %><br>
    <%= f.text_field :price, placeholder: "料金" %>
    <%= f.text_field :address, placeholder: "住所" %><br>
    <%= f.label :image_name, "画像 /"%>
    <%= f.file_field :image_name%><br>
    <%= f.submit "作成" %>
  <% end %>
 </div>

app/views/rooms/index.html.erb
<div class="search-form">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :address_keyword, value: @address_keyword, placeholder: "場所"%>
    <%= f.text_field :details_keyword, value: @details_keyword, placeholder: "キーワード" %>
    <%= f.submit "検索" %>
  <% end %>
</div>

<h3 class="index-count">検索結果 <%= @rooms.count %>件</h3>
<div class="index">
  <% @rooms.each do | room | %>
    <%= link_to room_path(room), class: "room-item" do %>
     <%= image_tag room.image_name.url, size: "300x200" %>
       <h3> <%= room.name %> </h3>
       <p class="details"> <%= room.details %> </p>
       <p> <%= room.price %> 円</p>
       <p> <%= room.address %> </p>
     <% end %>
  <% end %>
</div>

app/views/rooms/myrooms.html.erb
<h2 class="menu"> 登録ルーム一覧</h2>
<div class="index">
  <% @rooms.each do | room | %>
  <div class="room-item">
    <%= link_to room_path(room) do %>
      <%= image_tag room.image_name.url, size: "300x200" %>
      <h3> <%= room.name %> </h3>
      <p class="details"> <%= room.details %> </p>
      <p> <%= room.price %> 円</p>
      <p> <%= room.address %> </p>
      <div class="room-edit">
        <p> <%= room.created_at.in_time_zone('Tokyo').strftime('%Y/%m/%d') %> </p>
     <% end %>
        <p> <%= link_to "編集", edit_room_path(room) %></p>
        <p> <%= link_to "削除", room, method: :delete, data: { confirm: "本当に削除しますか?" } %></p>
      </div>
   </div>
  <% end %>
</div>

app/views/rooms/new.html.erb
<div class="room-form">
  <%= form_with model:@room do |f| %>
    <%= f.text_field :name, placeholder: "名前" %><br>
    <%= f.text_area :details, placeholder: "詳細" %><br>
    <%= f.text_field :price, placeholder: "料金" %>
    <%= f.text_field :address, placeholder: "住所" %><br>
    <%= f.label :image_name, "画像 /"%>
    <%= f.file_field :image_name%><br>
    <%= f.submit "作成" %>
  <% end %>
 </div>

app/views/rooms/show.html.erb
<div class="show-top">
  <p><%= link_to "⬅︎戻る", :back, onclick: "history.back(); return false;",class: "back" %></p>
  <% if user_signed_in? && current_user.id == @room.user_id %>
    <div class="show-edit">
      <p> <%= link_to "編集", edit_room_path(@room) %> </p>
      <p> <%= link_to "削除", @room, method: :delete, data: { confirm: "本当に削除しますか?" } %> </p>
    </div>
  <% end %>
</div>
<div class="room-contents">
  <div class="room-image">
    <%= image_tag @room.image_name.url , size: "400x300" %>
  </div>
  <div class="room-text">
    <h1> <%= @room.name %> </h1><br>
    <p class="details"> <%= @room.details %> </p>
    <p> <%= @room.price %> 円</p>
    <p> <%= @room.address %> </p>
  </div>
</div>
<% if current_user %>
  <%= form_with(model: [ :confirm, @room, @room.reservations.build ], local: true, html: { class: 'reservation-form' }) do |f| %>
    <div class="form-field">
      <%= f.label :headcount, "人数" %>
      <%= f.text_field :headcount, placeholder: "1以上" %>
    </div>
    <div class="form-field">
      <%= f.label :check_in, "チェックイン" %>
      <%= f.date_field :check_in %>
    </div>
    <div class="form-field">
      <%= f.label :check_out, "チェックアウト" %>
      <%= f.date_field :check_out %>
    </div>
    <%= f.submit "予約する", class: "reservation-btn" %>
  <% end %>
<% end %>